# SPDX-License-Identifier: Apache-2.0
"""Build the CPython extension used by the notary's latency-sensitive host path."""

import os
from pathlib import Path
import runpy
import sys

from setuptools import Extension, setup
from setuptools.command.build_ext import build_ext
from setuptools.command.build_py import build_py

policy = runpy.run_path(str(Path(__file__).parent / "src/cuattest/_build_options.py"))
build_type = policy["validate_build_type"](os.environ.get("CUATTEST_BUILD_TYPE", "Release"))


class ConfiguredBuildExt(build_ext):
    def build_extensions(self):
        # distutils timestamps do not include compiler flags. Switching modes
        # in an existing checkout MUST rebuild, even without a source edit.
        self.force = True
        self.compiler.force = True
        super().build_extensions()


class ConfiguredBuildPy(build_py):
    def run(self):
        super().run()
        (Path(self.build_lib) / "cuattest/_build_info.py").write_text(
            f"# Generated by setup.py; do not edit.\nBUILD_TYPE = {build_type!r}\n"
        )

extensions = []
if sys.platform.startswith("linux"):
    extensions.append(
        Extension(
            "cuattest._native",
            ["src/cuattest/_native.cpp"],
            language="c++",
            libraries=["dl"],
            extra_compile_args=policy["native_options"](build_type),
        )
    )

setup(ext_modules=extensions, cmdclass={"build_ext": ConfiguredBuildExt, "build_py": ConfiguredBuildPy})
